

# --------------------------------
# BASE

server:
  port: 18087
  servlet.context-path: /v1.1


spring:
  profiles.active:
  - proj-default
  - proj-air
  #- proj-pro
  #- proj-aws
  #- proj-dfep
  #- proj-real
  h2.console:
    enabled: true
    path: /h2
    settings:
      trace: false
      web-allow-others: true
  datasource:
    url: jdbc:h2:tcp://localhost:9092/lightnetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
#    hikari:
#      jdbc-url: jdbc:h2:tcp://localhost:9092/lightnetdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      # jdbc-url: jdbc:h2:tcp://localhost:9092/lightnetdb;MODE=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#      # jdbc-url: jdbc:h2:mem:testdb
#      driver-class-name: org.h2.Driver
#      username: sa
#      password:
  jpa:
    show-sql: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    properties:
      hibernate.jdbc.time-zone: UTC+9
  data.rest:
    base-path: /api
    default-page-size: 5
    max-page-size: 50
  thymeleaf:
    enabled: true
    encoding: utf-8
    cache: false
    prefix: classpath:templates/
    suffix: .html
  servlet.multipart:
    enabled: true
    location: ~/FILES
    max-file-size: 5GB
    max-request-size: 5GB
  devtools:
    livereload.enabled: true


logging:
  file:
    path: logs/mapper/
    max-size: 10MB
    max-history: 30         # delete after a month
  pattern:
    console: "%clr(%d{HH:mm:ss} %p){magenta} - %m%n"
    file: "%d %-5level [%-10thread] [%-30logger{30}] - %m%n"
  level:
    root: info
    org.tain.*: info
    org.hibernate.SQL: info
    org.hibernate.type: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.thymeleaf: info
    org.h2.server.web: info
    
    #org.tain.utils.TransferStrAndJson: trace


---
# --------------------------------------------------------
# --------------------------------------------------------
# --------------------------------------------------------
spring.profiles: proj-default

proj-env:
  base:
    name: Lightnet API project
    program: KieaLightnet API program
    version: ver 1.1_2020.11.11
    comment: This is Lightnet API project.
    test-flag: true
  param:
    name: PARAM (default)
  job:
    name: JOB (default)
  json:
    name: JSON (default)
  url:
    name: URL (default)

---
# --------------------------------------------------------
# proj-local
spring.profiles: proj-air

proj-env:
  param:
    name: PARAM (air)
    home: /Users/kang-air
    base: /KANG/lightnet/20201120
    info-path: /jsonInfo
    data-path: /jsonData
  job:
    name: JOB (air)
  json:
    name: JSON (air)
    apis-info-file: apis.json
    error-info-file: error.json
  url:
    name: URL (air)
    # lightnet1: http://localhost:18888
    # lightnet11: http://localhost:18888
    lightnet1: https://test-public.lightnetapis.io/v1
    lightnet11: https://test-public.lightnetapis.io/v1.1
    auth: http://localhost:18081/v1.1
    link: http://localhost:18082/v1.1
    mapper: http://localhost:18087/v1.1

---
# --------------------------------------------------------
# proj-test
spring.profiles: proj-pro

proj-env:
  param:
    name: PARAM (pro)
    home: /Users/kangmac
    base: /KANG/lightnet/20201120
    info-path: /jsonInfo
    data-path: /jsonData
  job:
    name: JOB (pro)
  json:
    name: JSON (pro)
    apis-info-file: apis.json
    error-info-file: error.json
  url:
    name: URL (pro)
    lightnet1: https://test-public.lightnetapis.io/v1
    lightnet11: https://test-public.lightnetapis.io/v1.1
    auth: http://localhost:18081/v1.1
    link: http://localhost:18082/v1.1
    mapper: http://localhost:18087/v1.1

---
# --------------------------------------------------------
# proj-aws
spring.profiles: proj-aws

proj-env:
  param:
    name: PARAM (aws)
  job:
    name: JOB (aws)
  json:
    name: JSON (aws)
  url:
    name: URL (aws)

---
# --------------------------------------------------------
# proj-dfep
spring.profiles: proj-dfep

proj-env:
  param:
    name: PARAM (dfep)
    home: /hw01/ibridge
    base: /KANG/lightnet/20201120
    info-path: /jsonInfo
    data-path: /jsonData
  job:
    name: JOB (dfep)
  json:
    name: JSON (dfep)
    apis-info-file: apis.json
    error-info-file: error.json
  url:
    name: URL (dfep)
    lightnet1: https://test-hawis.lightnetapis.io/v1
    lightnet11: https://test-hawis.lightnetapis.io/v1.1
    auth: http://localhost:18081/v1.1
    link: http://localhost:18082/v1.1
    mapper: http://localhost:18087/v1.1

---
# --------------------------------------------------------
# proj-real
spring.profiles: proj-real

proj-env:
  param:
    name: PARAM (real)
  job:
    name: JOB (real)
  json:
    name: JSON (real)
  url:
    name: URL (real)


